name: Test Build and Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: testing
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RAILS_4_SSH_HOST }}
          username: ${{ secrets.RAILS_4_SSH_USER }}
          key: ${{ secrets.RAILS_4_SSH_PRIVATE_KEY }}
          script: |
            whoami
            ls -al

      - name: SSH successfully
        run: echo "Deploy step completed successfully"
