name: Test Build and Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: testing
    runs-on: ubuntu-20.04

    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn3

      - name: Configure OpenVPN
        run: |
          echo "${{ secrets.VPN_CLIENT_CONFIG }}" > client.ovpn
          sudo openvpn3 config-import --config client.ovpn

      - name: Start Open VPN 3
        run: |
          sudo openvpn3 session-start --config client.ovpn

      # - name: SSH to EC2 and Deploy
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.RAILS_4_SSH_HOST }}
      #     username: ${{ secrets.RAILS_4_SSH_USER }}
      #     key: ${{ secrets.RAILS_4_SSH_PRIVATE_KEY }}
      #     script: |
      #       whoami
      #       ls -al

      # - name: SSH successfully
      #   run: echo "Deploy step completed successfully"
