name: Test Build and Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: testing
    runs-on: ubuntu-20.04

    steps:
      - name: Start Open VPN 3
      - uses: dbritto-dev/openvpn3-action@main
        with:
          vpn-client-config: ${{ secrets.VPN_CLIENT_CONFIG }}
          script: |
            sudo openvpn3 sessions-list

      # - name: SSH to EC2 and Deploy
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.RAILS_4_SSH_HOST }}
      #     username: ${{ secrets.RAILS_4_SSH_USER }}
      #     key: ${{ secrets.RAILS_4_SSH_PRIVATE_KEY }}
      #     script: |
      #       whoami
      #       ls -al

      # - name: SSH successfully
      #   run: echo "Deploy step completed successfully"
